// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO9_JaPJyWt8H1wAm9V2bh1JE4cLPs37A',
    appId: '1:400931778526:web:89fd3c18db660b8817f74f',
    messagingSenderId: '400931778526',
    projectId: 'semester-project-8bcce',
    authDomain: 'semester-project-8bcce.firebaseapp.com',
    storageBucket: 'semester-project-8bcce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyZCLuhXwbiDpKRJj1hIYSExc30A1U-aE',
    appId: '1:400931778526:android:e8248b1a25636fce17f74f',
    messagingSenderId: '400931778526',
    projectId: 'semester-project-8bcce',
    storageBucket: 'semester-project-8bcce.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu9kWrIbOm1KoEcE2i6JSZem-qZoS7QJ0',
    appId: '1:400931778526:ios:d437dd903bf310e017f74f',
    messagingSenderId: '400931778526',
    projectId: 'semester-project-8bcce',
    storageBucket: 'semester-project-8bcce.appspot.com',
    iosBundleId: 'com.example.eventManagementApp',
  );
}
